### ISSUE TITLE
Repo Layout Suggestion

### ISSUE THREAD

**Issue by geoffmcl** [fgx/crossfeed-dailies#3]
Since at present this is destined to grow each day, I suggest we move all the `csv` files to a sub-directory `csv`, and the `htm'` likewise to a sub-folder...

It is a pain for viewers to have to scroll down a growing long list of files before they reach an explanation... ie, I think it better to push multiple files down in the directory structure leaving a simple short root folder, mainly the readme.md...

It would be good to do this sooner than later, as more things get to depend on their location...

**Comment by pedromorgan** [comment]
yes good idea

**Comment by theo-armour** [comment]
@geoffmcl 

When there's day by day files involved, it might also be a nice idea to keep them directories with year numbers.

BTW, the current 3D replay always loads the latest file by default:

## [Globe Crossfeed Replay](http://fgx.github.io/sandbox/globe-crossfeed-replay/)

**Comment by geoffmcl** [comment]
Ok, have effected the move... and maybe later as suggested we could add year numbers...

But for now all moved simply... thanks...
