### ISSUE TITLE
How to show the html pages, in browser

### ISSUE THREAD

**Issue by geoffmcl** [fgx/crossfeed-dailies#4]
I have now moved the two htm files into the `html` folder, and will shortly add more, but...

But need a reminder of how to display this `html` folder as a web page? Theo, you seem to do this all the time... in a way... how?

Seems I can use - http://htmlpreview.github.io/?https://github.com/fgx/crossfeed-dailies/blob/gh-pages/html/20160806.htm - and that works for that page, but I do not see this `htmlpreview` in Theo's links, but maybe I missed it...

And what if I wanted to add an `index.htm`, which had internal links to the various other pages, how to link from that `index` to the other pages...

In the HTML Tidy project, Jim set up a DNS like link, to api.tidy.org, from the repo  https://github.com/htacg/html-tidy.org.api... then any push to that repo, added the change to the html page display... Is something similar possible here?

But that tidy stuff is also further complicated that the pages start as markdown, run by yaml... at this stage I prefer to physically generate the html locally, and just push it whole...

This is way out of my depth ;=))

I could of course, easily have a page on my geoffair.org site... and maybe display it as say `cf-stats.geoffair.org` or something... that I think I could do...

Any help appreciated... thanks...

**Comment by theo-armour** [comment]
I use the GitHub Pages feature a lot

So this repo is already set with the gh--pages branch as the default

So just and an index.html and go to

FGx.github.io/crossfeed-dailies

And then go there in your browser

oops. there's already one there....

**Comment by geoffmcl** [comment]
Ha ha ha LOL... that was too easy ;=))

At first had a scare that it had not worked... seems to take a few seconds **after** the `push`... 

But this is exactly what I was looking for... I will now begin the add more summaries, now and again...

Thanks again...

**Comment by theo-armour** [comment]
hard reload can speed things up

http://www.code-pal.com/quick-tip-clear-cache-hard-refresh-on-chrome/

debug console / f12 / must be open for the choices to appear
