### ISSUE TITLE
Mapping.

### ISSUE THREAD

**Issue by pedromorgan** [fgx/crossfeed-dailies#5]
Well @theo-armour and @geoffmcl 

This is most useful doc ever for me..

https://www.ordnancesurvey.co.uk/docs/support/guide-coordinate-systems-great-britain.pdf

**Comment by theo-armour** [comment]
@pedromorgan 

I wrote nice long thanking reply a couple of days ago. bit looks like I forgot to push the green - comment - button,  ;-(

Thanks. Very good link.

**Comment by geoffmcl** [comment]
@pedromorgan thanks Pete... very edifying pdf... 

I think I begin to understand ;=))

**Comment by theo-armour** [comment]
thanks again...
